baseurl = "https://spurs21.github.io/MyWorld/"
title = "Gray Xu"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
author = "Gray Xu"
info = "Backend Developer"
description = "Gray Xu's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/profile.png"
#gravatar = "john.doe@example.com"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2024

enableTwemoji = true

colorScheme = "dark"
hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Spurs21/"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/gray-xu-1898b3313/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"